2018-02-01 22:38:07,426 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-01 22:38:18,828 ERROR: Exception on /edit_profile [POST] [in /home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/tk/PycharmProjects/microblog/app/routes.py", line 24, in edit_profile
    db.session.commit()
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2243, in flush
    self._flush(objects)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2369, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2333, in _flush
    flush_context.execute()
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/tk/PycharmProjects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username [SQL: u'UPDATE user SET username=?, about_me=? WHERE user.id = ?'] [parameters: (u'john', u'a cat', 1)] (Background on this error at: http://sqlalche.me/e/gkpj)
2018-02-01 22:44:03,903 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-04 16:56:09,376 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-12 22:18:30,819 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-12 22:18:59,885 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-12 22:19:51,254 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-12 22:20:27,629 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-12 22:20:47,873 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-12 22:21:09,385 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-13 22:26:45,896 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-13 22:29:03,489 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-13 22:41:44,822 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
2018-02-13 22:42:13,375 INFO: Microblog startup [in /home/tk/PycharmProjects/microblog/app/__init__.py:41]
